name: Config Update

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Setup sing-box"
      run: |
        sudo mkdir -p /etc/apt/keyrings &&
        sudo curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc &&
        sudo chmod a+r /etc/apt/keyrings/sagernet.asc &&
        echo '
        Types: deb
        URIs: https://deb.sagernet.org/
        Suites: *
        Components: *
        Enabled: yes
        Signed-By: /etc/apt/keyrings/sagernet.asc
        ' | sudo tee /etc/apt/sources.list.d/sagernet.sources &&
        sudo apt-get update &&
        sudo apt-get install -y sing-box

    - name: Set up Python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests pyyaml

    - name: Create output directories
      run: |
        mkdir -p ./data/rule_json ./data/rule_srs

    - name: Run script
      run: python convert.py
      working-directory: ./data/

    - name: Move files to rule_json and rule_srs
      run: |
        mv ./data/*.json ./data/rule_json/ 2>/dev/null || true
        mv ./data/*.srs ./data/rule_srs/ 2>/dev/null || true

    - name: Commit and push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add ./data/rule_json/*.json ./data/rule_srs/*.srs

        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        else
          git commit -m "Update rules"
          git push
        fi

  cleanup-workflow-runs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
    - name: Delete old workflow runs and keep latest 1
      uses: actions/delete-workflow-runs@v3
      with:
        retain_runs: 1
        delete_workflow_pattern: 'main.yml'
